import React from 'react';
import { AlertCircle, Clock, Database, Layers } from 'lucide-react';
import AnimateOnScroll from './common/AnimateOnScroll';

const ProblemStats = () => {
  const stats = [
    {
      icon: <Layers size={28} />,
      color: 'from-teal-500/20 to-teal-500/5',
      iconColor: 'text-teal-500',
      borderColor: 'group-hover:shadow-glow-teal',
      title: "10+ Disconnected Sources",
      description: "Drone imagery, cadastral maps, and municipal records sit in silos with no unified pipeline."
    },
    {
      icon: <Clock size={28} />,
      color: 'from-amber-500/20 to-amber-500/5',
      iconColor: 'text-amber-500',
      borderColor: 'group-hover:shadow-glow-amber',
      title: "Slow Manual Workflows",
      description: "Labor-intensive GIS integration causes immense delays in urban land administration."
    },
    {
      icon: <AlertCircle size={28} />,
      color: 'from-rose-500/20 to-rose-500/5',
      iconColor: 'text-rose-500',
      borderColor: '',
      title: "Error-Prone Integration",
      description: "Manual alignment leads to boundary overlaps, gaps, and inconsistent property records."
    },
    {
      icon: <Database size={28} />,
      color: 'from-blue-500/20 to-blue-500/5',
      iconColor: 'text-blue-500',
      borderColor: 'group-hover:shadow-glow-blue',
      title: "Delayed Finalization",
      description: "Weeks of manual verification required before a cadastral record can be officially finalized."
    }
  ];

  return (
    <section id="problem" className="section-spacing bg-white dark:bg-slate-900 border-b border-slate-200 dark:border-slate-800 transition-colors duration-200">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <AnimateOnScroll className="text-center max-w-3xl mx-auto mb-14 lg:mb-16">
          <h2 className="section-title">The Challenge in Urban Land Records</h2>
          <p className="section-subtitle">
            Current systems struggle to efficiently process the massive volume of geospatial data generated by modern survey programs, leading to bottlenecks and inaccuracies.
          </p>
        </AnimateOnScroll>

        <AnimateOnScroll
          className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 lg:gap-8"
          staggerChildren={0.1}
        >
          {stats.map((stat, index) => (
            <div
              key={index}
              className={`card-glass card-hover-lift p-8 flex flex-col items-center text-center group ${stat.borderColor}`}
            >
              {/* Icon with gradient glow */}
              <div className={`relative mb-6`}>
                <div className={`absolute inset-0 bg-gradient-radial ${stat.color} rounded-full blur-xl scale-150 opacity-60`} />
                <div className={`relative w-16 h-16 rounded-2xl bg-gradient-to-br ${stat.color} border border-slate-200/40 dark:border-slate-700/40 flex items-center justify-center shadow-sm group-hover:scale-110 transition-transform duration-300`}>
                  <span className={stat.iconColor}>{stat.icon}</span>
                </div>
              </div>
              <h3 className="text-lg font-bold text-navy-800 dark:text-slate-100 mb-3">{stat.title}</h3>
              <p className="text-slate-600 dark:text-slate-400 text-sm leading-relaxed">
                {stat.description}
              </p>
            </div>
          ))}
        </AnimateOnScroll>
      </div>
    </section>
  );
};

export default ProblemStats;
